name = "Example8"
uuid = "7c0fc052-22b7-40d7-96e2-46d76cd90286"
authors = ["Jakub Sielewicz"]
version = "0.1.0"

[deps]
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"

[compat]
DocumenterTools = "0.1"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
